AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Service Catalog execution role

Parameters:
  DeploymentOu:
    Type: String
    Description: The OU to deploy the StackSet to
    Default: r-c834
  DeploymentRegion:
    Type: String
    Description: The region to deploy the StackSet to
    Default: us-east-1

Resources:
  ServiceCatalogExecutionRoleStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: ServiceCatalogExecutionRole
      Description: Execution Role for Service Catalog account StackSets
      PermissionModel: SERVICE_MANAGED
      ManagedExecution:
        Active: true
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: true
      OperationPreferences:
        FailureToleranceCount: 0
        MaxConcurrentCount: 1
        RegionConcurrencyType: PARALLEL
      Parameters:
        - ParameterKey: AdministratorAccountId
          ParameterValue: 905418259160
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref DeploymentOu
          Regions:
            - !Ref DeploymentRegion
      Capabilities:
        - CAPABILITY_NAMED_IAM
      TemplateBody: |
        AWSTemplateFormatVersion: '2010-09-09'
        Description: AWS Service Catalog execution role

        Parameters:
          AdministratorAccountId:
            Type: String
            Description: AWS Account Id of the administrator account (the account in which StackSets will be created).
            MaxLength: 12
            MinLength: 12

        Resources:
          AWSCloudFormationStackSetExecutionRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: AWSCloudFormationStackSetExecutionRole
              AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Effect: Allow
                    Principal:
                      AWS:
                        - !Ref AdministratorAccountId
                    Action:
                      - sts:AssumeRole
              Path: /
              ManagedPolicyArns:
                - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess

