AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Service Catalog Products

Resources:
  GitHubCodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: ServerlessOps GitHub (Svc Cat)
      ProviderType: GitHub

  # Portfolios
  BillingPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: Billing
      Description: "Billing & Cost Products"
      ProviderName: ServerlessOps

  CicdPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: CI/CD
      Description: "CI/CD Products"
      ProviderName: ServerlessOps


  # Products
  BillingAlarmsProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Billing Alarms
      Description: Account Billing Alarms
      Owner: ServerlessOps
      SourceConnection:
        Type: CODESTAR
        ConnectionParameters:
          CodeStar:
            ConnectionArn: !Ref GitHubCodeStarConnection
            Repository: ServerlessOpsIO/aws-service-catalog-products
            Branch: main
            ArtifactPath: products/billing-alarms/product.yaml

  BillingAlarmsProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref BillingPortfolio
      ProductId: !Ref BillingAlarmsProduct


  SamDeploymentProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: AWS SAM Deployment
      Description: AWS SAM deployment resources
      Owner: ServerlessOps
      SourceConnection:
        Type: CODESTAR
        ConnectionParameters:
          CodeStar:
            ConnectionArn: !Ref GitHubCodeStarConnection
            Repository: ServerlessOpsIO/aws-service-catalog-products
            Branch: main
            ArtifactPath: products/sam-deployment/product.yaml

  SamDeploymentProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref CicdPortfolio
      ProductId: !Ref SamDeploymentProduct


  GhaBuildProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: GHA Build Account
      Description: GHA build account resources
      Owner: ServerlessOps
      SourceConnection:
        Type: CODESTAR
        ConnectionParameters:
          CodeStar:
            ConnectionArn: !Ref GitHubCodeStarConnection
            Repository: ServerlessOpsIO/aws-service-catalog-products
            Branch: main
            ArtifactPath: products/gha-build/product.yaml

  GhaBuildProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref CicdPortfolio
      ProductId: !Ref GhaBuildProduct
