Metadata:
  localTemplateFile: &template_body ./products/products.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Service Catalog account setup

Parameters:
  AwsOrganizationId:
    Type: String
    Description: The AWS Organization Id

  TargetOuIds:
    Type: CommaDelimitedList
    Description: List of OUs

  TargetRegions:
    Type: CommaDelimitedList
    Description: List of regions

  GitHubSha:
    Type: String
    Description: GitHub SHA

Resources:
  CfnTemplateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'aws-service-catalog-templates-${AWS::AccountId}-${AWS::Region}'
      Tags:
        - Key: org:cicd:writable
          Value: "true"

  CfnTemplateBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CfnTemplateBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject*'
              - 's3:List*'
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${CfnTemplateBucket}/*'
            Condition:
              StringEquals:
                "aws:PrincipalOrgID":
                  - !Ref AwsOrganizationId

  #OrgProductsStack:
  #  Type: AWS::Serverless::Application
  #  Properties:
  #    Location: "./products/products.yaml"
  #    Parameters:
  #      CfnTemplateBucket: !Ref CfnTemplateBucket
  #      GitHubSha: !Ref GitHubSha

  OrgProductsStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: OrgProducts
      Description: Organization products
      Parameters:
        - ParameterKey: CfnTemplateBucket
          ParameterValue: !Ref CfnTemplateBucket
        - ParameterKey: GitHubSha
          ParameterValue: !Ref GitHubSha
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref TargetOuIds
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *template_body