AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Service Catalog account setup

Parameters:
  ServiceBranch:
    Type: String
    Description: The branch of this deployment
    Default: main

Resources:
  CfnTemplateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'aws-service-catalog-templates-${AWS::AccountId}-${AWS::Region}'

  CfnTemplateBucketNameSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/service-catalog/${ServiceBranch}/CfnTemplateBucketName'
      Type: String
      Value: !Ref CfnTemplateBucket

  # Delegated Access role for Service Catalog
  # ref.https://aws.amazon.com/blogs/mt/simplify-sharing-your-aws-service-catalog-portfolios-in-an-aws-organizations-setup/
  AWSCloudFormationStackSetAdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AssumeRole-AWSCloudFormationStackSetExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - !Sub 'arn:${AWS::Partition}:iam::*:role/AWSCloudFormationStackSetExecutionRole'
