AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Service Catalog

Parameters:
  CfnTemplateBucket:
    Type: String
    Description: The S3 bucket CloudFormation templates are stored

  GitHubSha:
    Type: String
    Description: GitHub SHA

Resources:
  ServiceCatalogCfnExecIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "ServiceCatalogCfnExecIamRole-${AWS::Region}"
      Description: "Service Catalog CFN execution role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: servicecatalog.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # Portfolios
  NetworkingPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: Networking
      Description: "Networking products"
      ProviderName: ServerlessOps

  NetworkingPortfolioPrincipalAdmin:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref NetworkingPortfolio
      PrincipalARN: !Sub 'arn:${AWS::Partition}:iam:::role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AWSAdministratorAccess_*'
      PrincipalType: IAM_PATTERN

  NetworkingPortfolioPrincipalPowerUser:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref NetworkingPortfolio
      PrincipalARN: !Sub 'arn:${AWS::Partition}:iam:::role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AWSPowerUserAccess_*'
      PrincipalType: IAM_PATTERN

  # Products
  VpcProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: VPC
      Description: VPC networking
      Owner: ServerlessOps
      ProvisioningArtifactParameters:
        - Name: latest
          Description: latest release
          Info:
            LoadTemplateFromURL: !Sub 'https://${CfnTemplateBucket}.s3.amazonaws.com/${GitHubSha}/networking/vpc.yaml'


  VpcProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref NetworkingPortfolio
      ProductId: !Ref VpcProduct


  DnsProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: DNS Zone
      Description: DNS zone
      Owner: ServerlessOps
      ProvisioningArtifactParameters:
        - Name: latest
          Description: latest release
          Info:
            LoadTemplateFromURL: !Sub 'https://${CfnTemplateBucket}.s3.amazonaws.com/${GitHubSha}/networking/dns.yaml'

  DnsProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref NetworkingPortfolio
      ProductId: !Ref DnsProduct

  DnsLaunchConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      Description: "DNS zone launch constraint"
      PortfolioId: !Ref NetworkingPortfolio
      ProductId: !Ref DnsProduct
      RoleArn: !GetAtt ServiceCatalogCfnExecIamRole.Arn
