AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Billing Alarms

Resources:
  BillingAlarmSnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: BillingAlarms
      Subscription:
        - Endpoint: !Sub "admin+aws-billing-${AWS::AccountId}@serverlessops.io"
          Protocol: email

  BillingAlarm10:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: 1
      Period: 21600
      Namespace: "AWS/Billing"
      MetricName: "EstimatedCharges"
      Dimensions:
        - Name: "Currency"
          Value: "USD"
      Statistic: "Maximum"
      Threshold: 10
      AlarmActions:
        - Ref: BillingAlarmSnsTopic

  BillingAlarm25:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: 1
      Period: 21600
      Namespace: "AWS/Billing"
      MetricName: "EstimatedCharges"
      Dimensions:
        - Name: "Currency"
          Value: "USD"
      Statistic: "Maximum"
      Threshold: 25
      AlarmActions:
        - Ref: BillingAlarmSnsTopic

  BillingAlarm50:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: 1
      Period: 21600
      Namespace: "AWS/Billing"
      MetricName: "EstimatedCharges"
      Dimensions:
        - Name: "Currency"
          Value: "USD"
      Statistic: "Maximum"
      Threshold: 50
      AlarmActions:
        - Ref: BillingAlarmSnsTopic