AWSTemplateFormatVersion: '2010-09-09'
Description: DNS domain

Parameters:
  ZoneName:
    Type: String
    Description: "DNS domain name"
  CustomResourceTarget:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "Custom resource target"
    Default: "/org/cicd/CustomResourceTopic"

Resources:
  DnsZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: !Ref ZoneName

  DnsZoneNameSsmParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/org/dns/ZoneName"
      Type: String
      Value: !Ref ZoneName

  DnsZoneIdSsmParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/org/dns/ZoneId"
      Type: String
      Value: !Ref DnsZone

  DnsZoneNsServersSsmParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/org/dns/ZoneNameServers"
      Type: StringList
      Value: !Join [ ',', !GetAtt DnsZone.NameServers ]

  RegisterDnsZone:
    Type: Custom::RegisterDnsZone
    Properties:
      ServiceToken: !Ref CustomResourceTarget
      ServiceTimeout: 60
      ZoneName: !Ref ZoneName
      ZoneNameServers: !GetAtt DnsZone.NameServers